apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openvpn-keystore-secret
data:
  server.key: {{ .Files.Get "certs/server.key" | b64enc }}
  ca.crt: {{ .Files.Get "certs/ca.crt" | b64enc }}
  server.crt: {{ .Files.Get "certs/server.crt" | b64enc }}
  dh.pem: {{ .Files.Get "certs/dh.pem" | b64enc }}
  